### ISSUE TITLE
Pressing keyboard binded button when alive message

### ISSUE THREAD

**Issue by ChickenDipper1** [ItsAmmarB/DeathScript#11]
Hi,
Sorry one other issue from binding the key.

I bound E to respawn, the only issue remaining is the message that appears "you are already alive" I was just wondering if it is possible for this check/message to only run if you are in a downed state?

Would it be better if I just removed the message?

Also when respawning food/water/stress do not refill, do I need another script for this?

Thanks.

**Comment by ChickenDipper1** [comment]
Not to worry, just commented out the line for the message.
And added TriggerEvent('esx_basicneeds:resetStatus'); to cl_index.js.

Thanks

**Comment by ItsAmmarB** [comment]
hey, I've found why it happened, again, because of my half working brain at the time 🤣 

Fixed in [Master Branch](https://github.com/ItsAmmarB/DeathScript)

**Comment by ItsAmmarB** [comment]
it SHOULD be fixed now, release [v2.1.4-a](https://github.com/ItsAmmarB/DeathScript/releases/tag/v2.1.4-a)

Again, thanks for the feedback 🙏
