### ISSUE TITLE
Remnant of resource causing black screen

### ISSUE THREAD

**Issue by htekwani1** [ItsAmmarB/DeathScript#14]
Hello,
I attempted to remove this resource and replace it with another death script but there is a remnant of the script that says "press E to respawn" when a character dies. However, when you press E you get a black screen that requires a relog. 

I've tried deleting server cache and restarting multiple times, at this point I'm lost. I would appreciate any insight as to why this is happening, as it stands we have no way to revive/respawn.

**Comment by ItsAmmarB** [comment]
Hey,

Sorry for wait, I was too busy the past few months, but the "press E to respawn" message isn't part of my script.

Hope you found it, good luck!
