### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by kelopuu** [ItsAmmarB/DeathScript#17]
i get insuffient permissions this is my permission setup ##admin config
add_ace group.admin vMenu.NoClip allow
add_ace group.admin allow
add_ace group.admin commands.adrev allow
add_ace group.admin commands.adres allow
add_ace group.admin commands.restart allow
add_ace group.admin commands.start allow
add_ace group.admin commands.stop allow

**Comment by ItsAmmarB** [comment]
Replace commands with DeathScript

**Comment by ItsAmmarB** [comment]
Use those 
```
add_ace group.admin "DeathScript.adrev" allow
add_ace group.admin "DeathScript.adres" allow
```

**Comment by kelopuu** [comment]
ty very much!

**Comment by ItsAmmarB** [comment]
not a problem
