### ISSUE TITLE
Respawn not taking character to hospital!

### ISSUE THREAD

**Issue by SkiddyPiglet** [ItsAmmarB/DeathScript#2]
Hi there, I can't seem to figure out why when using the /respawn command it does not teleport the character to hospital, instead it does the cloud animation but then revives them at their death location.
I have not changed your config in anyway so far.

Do you have any solution to my issue?

Thank you, I look forward to your response.

**Comment by ItsAmmarB** [comment]
Hey,
Is there any error being thrown in the console or game chat?
P.S: Also; what server artifact version you're using?

**Comment by ItsAmmarB** [comment]
I've tried for more than 2 hours to produce the issue with no luck, if you can provide the steps to reproduce the issue or error message, that would be a really good starting point.

Also, the server artifact version is needed.

**Comment by Juu0** [comment]
> I've tried for more than 2 hours to produce the issue with no luck, if you can provide the steps to reproduce the issue or error message, that would be a really good starting point.
> 
> Also, the server artifact version is needed.

i know this is unrelated but is there a preview to this script ?

**Comment by ItsAmmarB** [comment]
> > I've tried for more than 2 hours to produce the issue with no luck, if you can provide the steps to reproduce the issue or error message, that would be a really good starting point.
> > Also, the server artifact version is needed.
> 
> i know this is unrelated but is there a preview to this script ?

no, there isn't a preview of this script, because it is just easy to use and straightforward

**Comment by Juu0** [comment]
> > > I've tried for more than 2 hours to produce the issue with no luck, if you can provide the steps to reproduce the issue or error message, that would be a really good starting point.
> > > Also, the server artifact version is needed.
> > 
> > 
> > i know this is unrelated but is there a preview to this script ?
> 
> no, there isn't a preview of this script, because it is just easy to use and straightforward

is there a way for the timer to update every 30 seconds in the chat, instead of it being a timer?

**Comment by ItsAmmarB** [comment]
> > > > I've tried for more than 2 hours to produce the issue with no luck, if you can provide the steps to reproduce the issue or error message, that would be a really good starting point.
> > > > Also, the server artifact version is needed.
> > > 
> > > 
> > > i know this is unrelated but is there a preview to this script ?
> > 
> > 
> > no, there isn't a preview of this script, because it is just easy to use and straightforward
> 
> is there a way for the timer to update every 30 seconds in the chat, instead of it being a timer?

not that I have done anything to do that, but if you want you can modify it to suit your needs and desires

**Comment by Juu0** [comment]
> > > > > I've tried for more than 2 hours to produce the issue with no luck, if you can provide the steps to reproduce the issue or error message, that would be a really good starting point.
> > > > > Also, the server artifact version is needed.
> > > > 
> > > > 
> > > > i know this is unrelated but is there a preview to this script ?
> > > 
> > > 
> > > no, there isn't a preview of this script, because it is just easy to use and straightforward
> > 
> > 
> > is there a way for the timer to update every 30 seconds in the chat, instead of it being a timer?
> 
> not that I have done anything to do that, but if you want you can modify it to suit your needs and desires

I'm not really good at coding, is it possible to enlarge the font of the timer? and move its position?

**Comment by Juu0** [comment]
also my game crashes everytime it tries to respawn me, and it gives me this code


Error GTA5_b1604.exe!sub_1408E4320 (0xf0)

[Main Instruction]
GTA5_b1604.exe!sub_1408E4320 (0xf0)

[Content]
An error at GTA5_b1604.exe!sub_1408E4320 (0xf0) caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.

Legacy crash hash: kansas-mississippi-zebra
Stack trace:
  GTA5_b1604.exe!sub_1408E4320 (0xf0)
  GTA5_b1604.exe!sub_140907D78 (0x70)
  GTA5_b1604.exe!sub_14091DDD4 (0x28)
  GTA5_b1604.exe!sub_1409181D0 (0x31)
  GTA5_b1604.exe!CScene::PreSceneUpdate (0x26)
  gta-core-five.dll!rage::RunEntries (0x62) (GameSkeleton.cpp:193)
  gta-core-five.dll!rage::gameSkeleton_updateBase::RunGroup (0x68) (GameSkeleton.cpp:220)


[^] Hide details  [Save information] [Close]

[Expanded Information]
Crash signature: GTA5_b1604.exe+8E4410
Report ID: si-9f27cbc726e14c0fa34612e5e4308398
You can press Ctrl-C to copy this message and paste it elsewhere.
