### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by CJ2028** [ItsAmmarB/DeathScript#20]
its not really an issue more like some help, im not sure where to put the commands to give me permission to AdRes ive tried placing it in different parts but it ends up just not working at all, any advise?

**Comment by ItsAmmarB** [comment]
Hey, 

not a problem at all, so;
if you have a permission.cfg file in your main FiveM server directory, it would be there, otherwise; in the server.cfg

**Comment by CJ2028** [comment]
ok cool ill have a go where abouts do i put it in my server cfg, soz im a bit new lol

**Comment by ItsAmmarB** [comment]
anywhere really, as long as it's after sv_licenseKey

**Comment by CJ2028** [comment]
ok thanks what commands do i do? just so i dont write anything wrong

**Comment by ItsAmmarB** [comment]
are you giving it to one person? or a group of people?

**Comment by CJ2028** [comment]
just to me for now i havent made a group thing yet, the only time ive used ace permissions is for my vmenu

**Comment by ItsAmmarB** [comment]
do you know what an identifier is?

**Comment by CJ2028** [comment]
a group would be nice at some point lol

**Comment by ItsAmmarB** [comment]
> a group would be nice at some point lol

of course, it saves time managing permissions

**Comment by CJ2028** [comment]
its like if u want it to find a steam id or smt like what its looking for

**Comment by ItsAmmarB** [comment]
is the server hosted on your own pc?

**Comment by CJ2028** [comment]
its not

**Comment by CJ2028** [comment]
zap

**Comment by ItsAmmarB** [comment]
okay, so get your own steam profile link, then [use this link](https://steamid.pro/)..

paste your steam profile link in the search field, then scroll down a bit, you'll find a table, one of the rows is called ``FiveM, HEX``

copy it and replace STEAM with it in this syntax

``add_ace identifier.STEAM DeathScript allow``

and put it in your server.cfg/permissions.cfg if you have one

**Comment by CJ2028** [comment]
dont mind the other bits just wanted to show ya where i put it is that the right place?


add_ace group.admin webadmin allow
add_principal identifier.steam:110000143c56122 group.admin
add_principal identifier.steam:11000013d688129 group.admin
add_ace identifier.steam:110000143c56122 DeathScript allow <--------------------
add_ace group.admin easyadmin allow
set ea_moderationNotification "false"
set ea_minIdentifierMatches 2

**Comment by CJ2028** [comment]
it workedddd thanks so much

**Comment by CJ2028** [comment]
do u make custom scripts for people at all?

**Comment by CJ2028** [comment]
ofc not free but yk lol

**Comment by ItsAmmarB** [comment]
depends on the needs

**Comment by ItsAmmarB** [comment]
> it workedddd thanks so much

not a problem :D

**Comment by CJ2028** [comment]
i need some things made im not sure if its hard to do so if it is let me know lol i dont want to expect too much

**Comment by CJ2028** [comment]
have you got discord?

**Comment by ItsAmmarB** [comment]
I sure do, I'll message you privately

**Comment by CJ2028** [comment]
yeah okay mine CJ_2022

**Comment by ItsAmmarB** [comment]
Got it, I'll send you a friend request in a sec, I'm closing this issue if you're not needing anything regarding this resource

**Comment by CJ2028** [comment]
na its all good now thanks man
