### ISSUE TITLE
Game crash on respawn

### ISSUE THREAD

**Issue by ItsAmmarB** [ItsAmmarB/DeathScript#4]
also my game crashes everytime it tries to respawn me, and it gives me this code

Error GTA5_b1604.exe!sub_1408E4320 (0xf0)

[Main Instruction]
GTA5_b1604.exe!sub_1408E4320 (0xf0)

[Content]
An error at GTA5_b1604.exe!sub_1408E4320 (0xf0) caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.

Legacy crash hash: kansas-mississippi-zebra
Stack trace:
  GTA5_b1604.exe!sub_1408E4320 (0xf0)
  GTA5_b1604.exe!sub_140907D78 (0x70)
  GTA5_b1604.exe!sub_14091DDD4 (0x28)
  GTA5_b1604.exe!sub_1409181D0 (0x31)
  GTA5_b1604.exe!CScene::PreSceneUpdate (0x26)
  gta-core-five.dll!rage::RunEntries (0x62) (GameSkeleton.cpp:193)
  gta-core-five.dll!rage::gameSkeleton_updateBase::RunGroup (0x68) (GameSkeleton.cpp:220)

[^] Hide details  [Save information] [Close]

[Expanded Information]
Crash signature: GTA5_b1604.exe+8E4410
Report ID: si-9f27cbc726e14c0fa34612e5e4308398
You can press Ctrl-C to copy this message and paste it elsewhere.

_Originally posted by @Juu0 in https://github.com/ItsAmmarB/DeathScript/issues/2#issuecomment-1100955097_

**Comment by ItsAmmarB** [comment]
that's weird, is it **every time** you respawn?

**Comment by Juu0** [comment]
yes everytime, no matter where i spawn. Its when the camera goes to the satellite animation

**Comment by ItsAmmarB** [comment]
what artifacts version are you running?
