### ISSUE TITLE
/respawn /adres ( Spawn Issue ) BUG

### ISSUE THREAD

**Issue by JesseJamesKILL** [ItsAmmarB/DeathScript#5]
When using Command /respawn or /adres teleports Player to Paleto Bay Hospital ((ONLY))

No matter where you are on the map it spawns the Player at Paleto Bay Hospital

**Comment by ItsAmmarB** [comment]
thank you for the feedback, I've managed to figure out why it was happening.
a fixed version is coming out soon

**Comment by ItsAmmarB** [comment]
This issue has been fixed in https://github.com/ItsAmmarB/DeathScript/commit/dea48daff903df8a919763318a5a85e37c928623

**Thank you again for your feedback**

**Comment by ItsAmmarB** [comment]
https://github.com/ItsAmmarB/DeathScript/releases/tag/v2.1.3
