### ISSUE TITLE
Revive with Carbine in Hand

### ISSUE THREAD

**Issue by zgriffin56** [ItsAmmarB/DeathScript#6]
When i use /revive, I revive with a Carbine in my hand and cannot get it out of my hand.  Can't change weapons or switch to empty hand.  What can I do?

**Comment by ItsAmmarB** [comment]
did you have the Carbine in your hand before dying? 
and did you die inside of a vehicle or on foot?
and lastly, which version of the script are you using?

**Comment by ItsAmmarB** [comment]
and if possible could you provide the steps to reproduce the issue? 
I'm unable to reproduce it
