### ISSUE TITLE
ace permissions

### ISSUE THREAD

**Issue by Calumjn98** [ItsAmmarB/DeathScript#9]
not so much of an issues im trying to add ace perms just to the revive part is there anywhay you can tell me where to restrict the command please

**Comment by ItsAmmarB** [comment]
Hey,
The "/revive" command only revives the person who is using it, and does not require any permission to use it.

**Comment by Calumjn98** [comment]
So it dosent revive someone else?

**Comment by ItsAmmarB** [comment]
No, the "/revive" only revives the person using it, on the other hand; "/adrev" aka. admin revive can revive the person using it and other people using their ID.
